// countries.js
const countries = [
  { name: 'Afghanistan', code: 'af', flag: 'https://flagcdn.com/af.svg' },
  { name: 'Albania', code: 'al', flag: 'https://flagcdn.com/al.svg' },
  { name: 'Algeria', code: 'dz', flag: 'https://flagcdn.com/dz.svg' },
  { name: 'Andorra', code: 'ad', flag: 'https://flagcdn.com/ad.svg' },
  { name: 'Angola', code: 'ao', flag: 'https://flagcdn.com/ao.svg' },
  { name: 'Antigua and Barbuda', code: 'ag', flag: 'https://flagcdn.com/ag.svg' },
  { name: 'Argentina', code: 'ar', flag: 'https://flagcdn.com/ar.svg' },
  { name: 'Armenia', code: 'am', flag: 'https://flagcdn.com/am.svg' },
  { name: 'Australia', code: 'au', flag: 'https://flagcdn.com/au.svg' },
  { name: 'Austria', code: 'at', flag: 'https://flagcdn.com/at.svg' },
  { name: 'Azerbaijan', code: 'az', flag: 'https://flagcdn.com/az.svg' },
  { name: 'Bahamas', code: 'bs', flag: 'https://flagcdn.com/bs.svg' },
  { name: 'Bahrain', code: 'bh', flag: 'https://flagcdn.com/bh.svg' },
  { name: 'Bangladesh', code: 'bd', flag: 'https://flagcdn.com/bd.svg' },
  { name: 'Barbados', code: 'bb', flag: 'https://flagcdn.com/bb.svg' },
  { name: 'Belarus', code: 'by', flag: 'https://flagcdn.com/by.svg' },
  { name: 'Belgium', code: 'be', flag: 'https://flagcdn.com/be.svg' },
  { name: 'Belize', code: 'bz', flag: 'https://flagcdn.com/bz.svg' },
  { name: 'Benin', code: 'bj', flag: 'https://flagcdn.com/bj.svg' },
  { name: 'Bhutan', code: 'bt', flag: 'https://flagcdn.com/bt.svg' },
  { name: 'Bolivia', code: 'bo', flag: 'https://flagcdn.com/bo.svg' },
  { name: 'Bosnia and Herzegovina', code: 'ba', flag: 'https://flagcdn.com/ba.svg' },
  { name: 'Botswana', code: 'bw', flag: 'https://flagcdn.com/bw.svg' },
  { name: 'Brazil', code: 'br', flag: 'https://flagcdn.com/br.svg' },
  { name: 'Brunei', code: 'bn', flag: 'https://flagcdn.com/bn.svg' },
  { name: 'Bulgaria', code: 'bg', flag: 'https://flagcdn.com/bg.svg' },
  { name: 'Burkina Faso', code: 'bf', flag: 'https://flagcdn.com/bf.svg' },
  { name: 'Burundi', code: 'bi', flag: 'https://flagcdn.com/bi.svg' },
  { name: 'Cabo Verde', code: 'cv', flag: 'https://flagcdn.com/cv.svg' },
  { name: 'Cambodia', code: 'kh', flag: 'https://flagcdn.com/kh.svg' },
  { name: 'Cameroon', code: 'cm', flag: 'https://flagcdn.com/cm.svg' },
  { name: 'Canada', code: 'ca', flag: 'https://flagcdn.com/ca.svg' },
  { name: 'Central African Republic', code: 'cf', flag: 'https://flagcdn.com/cf.svg' },
  { name: 'Chad', code: 'td', flag: 'https://flagcdn.com/td.svg' },
  { name: 'Chile', code: 'cl', flag: 'https://flagcdn.com/cl.svg' },
  { name: 'China', code: 'cn', flag: 'https://flagcdn.com/cn.svg' },
  { name: 'Colombia', code: 'co', flag: 'https://flagcdn.com/co.svg' },
  { name: 'Comoros', code: 'km', flag: 'https://flagcdn.com/km.svg' },
  { name: 'Congo', code: 'cg', flag: 'https://flagcdn.com/cg.svg' },
  { name: 'Costa Rica', code: 'cr', flag: 'https://flagcdn.com/cr.svg' },
  { name: "Côte d'Ivoire", code: 'ci', flag: 'https://flagcdn.com/ci.svg' },
  { name: 'Croatia', code: 'hr', flag: 'https://flagcdn.com/hr.svg' },
  { name: 'Cuba', code: 'cu', flag: 'https://flagcdn.com/cu.svg' },
  { name: 'Cyprus', code: 'cy', flag: 'https://flagcdn.com/cy.svg' },
  { name: 'Czech Republic', code: 'cz', flag: 'https://flagcdn.com/cz.svg' },
  { name: 'Denmark', code: 'dk', flag: 'https://flagcdn.com/dk.svg' },
  { name: 'Djibouti', code: 'dj', flag: 'https://flagcdn.com/dj.svg' },
  { name: 'Dominica', code: 'dm', flag: 'https://flagcdn.com/dm.svg' },
  { name: 'Dominican Republic', code: 'do', flag: 'https://flagcdn.com/do.svg' },
  { name: 'East Timor', code: 'tl', flag: 'https://flagcdn.com/tl.svg' },
  { name: 'Ecuador', code: 'ec', flag: 'https://flagcdn.com/ec.svg' },
  { name: 'Egypt', code: 'eg', flag: 'https://flagcdn.com/eg.svg' },
  { name: 'El Salvador', code: 'sv', flag: 'https://flagcdn.com/sv.svg' },
  { name: 'Equatorial Guinea', code: 'gq', flag: 'https://flagcdn.com/gq.svg' },
  { name: 'Eritrea', code: 'er', flag: 'https://flagcdn.com/er.svg' },
  { name: 'Estonia', code: 'ee', flag: 'https://flagcdn.com/ee.svg' },
  { name: 'Eswatini', code: 'sz', flag: 'https://flagcdn.com/sz.svg' },
  { name: 'Ethiopia', code: 'et', flag: 'https://flagcdn.com/et.svg' },
  { name: 'Fiji', code: 'fj', flag: 'https://flagcdn.com/fj.svg' },
  { name: 'Finland', code: 'fi', flag: 'https://flagcdn.com/fi.svg' },
  { name: 'France', code: 'fr', flag: 'https://flagcdn.com/fr.svg' },
  { name: 'Gabon', code: 'ga', flag: 'https://flagcdn.com/ga.svg' },
  { name: 'Gambia', code: 'gm', flag: 'https://flagcdn.com/gm.svg' },
  { name: 'Georgia', code: 'ge', flag: 'https://flagcdn.com/ge.svg' },
  { name: 'Germany', code: 'de', flag: 'https://flagcdn.com/de.svg' },
  { name: 'Ghana', code: 'gh', flag: 'https://flagcdn.com/gh.svg' },
  { name: 'Greece', code: 'gr', flag: 'https://flagcdn.com/gr.svg' },
  { name: 'Grenada', code: 'gd', flag: 'https://flagcdn.com/gd.svg' },
  { name: 'Guatemala', code: 'gt', flag: 'https://flagcdn.com/gt.svg' },
  { name: 'Guinea', code: 'gn', flag: 'https://flagcdn.com/gn.svg' },
  { name: 'Guinea-Bissau', code: 'gw', flag: 'https://flagcdn.com/gw.svg' },
  { name: 'Guyana', code: 'gy', flag: 'https://flagcdn.com/gy.svg' },
  { name: 'Haiti', code: 'ht', flag: 'https://flagcdn.com/ht.svg' },
  { name: 'Honduras', code: 'hn', flag: 'https://flagcdn.com/hn.svg' },
  { name: 'Hungary', code: 'hu', flag: 'https://flagcdn.com/hu.svg' },
  { name: 'Iceland', code: 'is', flag: 'https://flagcdn.com/is.svg' },
  { name: 'India', code: 'in', flag: 'https://flagcdn.com/in.svg' },
  { name: 'Indonesia', code: 'id', flag: 'https://flagcdn.com/id.svg' },
  { name: 'Iran', code: 'ir', flag: 'https://flagcdn.com/ir.svg' },
  { name: 'Iraq', code: 'iq', flag: 'https://flagcdn.com/iq.svg' },
  { name: 'Ireland', code: 'ie', flag: 'https://flagcdn.com/ie.svg' },
  { name: 'Israel', code: 'il', flag: 'https://flagcdn.com/il.svg' },
  { name: 'Italy', code: 'it', flag: 'https://flagcdn.com/it.svg' },
  { name: 'Jamaica', code: 'jm', flag: 'https://flagcdn.com/jm.svg' },
  { name: 'Japan', code: 'jp', flag: 'https://flagcdn.com/jp.svg' },
  { name: 'Jordan', code: 'jo', flag: 'https://flagcdn.com/jo.svg' },
  { name: 'Kazakhstan', code: 'kz', flag: 'https://flagcdn.com/kz.svg' },
  { name: 'Kenya', code: 'ke', flag: 'https://flagcdn.com/ke.svg' },
  { name: 'Kiribati', code: 'ki', flag: 'https://flagcdn.com/ki.svg' },
  { name: 'North Korea', code: 'kp', flag: 'https://flagcdn.com/kp.svg' },
  { name: 'South Korea', code: 'kr', flag: 'https://flagcdn.com/kr.svg' },
  { name: 'Kuwait', code: 'kw', flag: 'https://flagcdn.com/kw.svg' },
  { name: 'Kyrgyzstan', code: 'kg', flag: 'https://flagcdn.com/kg.svg' },
  { name: 'Laos', code: 'la', flag: 'https://flagcdn.com/la.svg' },
  { name: 'Latvia', code: 'lv', flag: 'https://flagcdn.com/lv.svg' },
  { name: 'Lebanon', code: 'lb', flag: 'https://flagcdn.com/lb.svg' },
  { name: 'Lesotho', code: 'ls', flag: 'https://flagcdn.com/ls.svg' },
  { name: 'Liberia', code: 'lr', flag: 'https://flagcdn.com/lr.svg' },
  { name: 'Libya', code: 'ly', flag: 'https://flagcdn.com/ly.svg' },
  { name: 'Liechtenstein', code: 'li', flag: 'https://flagcdn.com/li.svg' },
  { name: 'Lithuania', code: 'lt', flag: 'https://flagcdn.com/lt.svg' },
  { name: 'Luxembourg', code: 'lu', flag: 'https://flagcdn.com/lu.svg' },
  { name: 'Madagascar', code: 'mg', flag: 'https://flagcdn.com/mg.svg' },
  { name: 'Malawi', code: 'mw', flag: 'https://flagcdn.com/mw.svg' },
  { name: 'Malaysia', code: 'my', flag: 'https://flagcdn.com/my.svg' },
  { name: 'Maldives', code: 'mv', flag: 'https://flagcdn.com/mv.svg' },
  { name: 'Mali', code: 'ml', flag: 'https://flagcdn.com/ml.svg' },
  { name: 'Malta', code: 'mt', flag: 'https://flagcdn.com/mt.svg' },
  { name: 'Marshall Islands', code: 'mh', flag: 'https://flagcdn.com/mh.svg' },
  { name: 'Mauritania', code: 'mr', flag: 'https://flagcdn.com/mr.svg' },
  { name: 'Mauritius', code: 'mu', flag: 'https://flagcdn.com/mu.svg' },
  { name: 'Mexico', code: 'mx', flag: 'https://flagcdn.com/mx.svg' },
  { name: 'Micronesia', code: 'fm', flag: 'https://flagcdn.com/fm.svg' },
  { name: 'Moldova', code: 'md', flag: 'https://flagcdn.com/md.svg' },
  { name: 'Monaco', code: 'mc', flag: 'https://flagcdn.com/mc.svg' },
  { name: 'Mongolia', code: 'mn', flag: 'https://flagcdn.com/mn.svg' },
  { name: 'Montenegro', code: 'me', flag: 'https://flagcdn.com/me.svg' },
  { name: 'Morocco', code: 'ma', flag: 'https://flagcdn.com/ma.svg' },
  { name: 'Mozambique', code: 'mz', flag: 'https://flagcdn.com/mz.svg' },
  { name: 'Myanmar', code: 'mm', flag: 'https://flagcdn.com/mm.svg' },
  { name: 'Namibia', code: 'na', flag: 'https://flagcdn.com/na.svg' },
  { name: 'Nauru', code: 'nr', flag: 'https://flagcdn.com/nr.svg' },
  { name: 'Nepal', code: 'np', flag: 'https://flagcdn.com/np.svg' },
  { name: 'Netherlands', code: 'nl', flag: 'https://flagcdn.com/nl.svg' },
  { name: 'New Zealand', code: 'nz', flag: 'https://flagcdn.com/nz.svg' },
  { name: 'Nicaragua', code: 'ni', flag: 'https://flagcdn.com/ni.svg' },
  { name: 'Niger', code: 'ne', flag: 'https://flagcdn.com/ne.svg' },
  { name: 'Nigeria', code: 'ng', flag: 'https://flagcdn.com/ng.svg' },
  { name: 'North Macedonia', code: 'mk', flag: 'https://flagcdn.com/mk.svg' },
  { name: 'Norway', code: 'no', flag: 'https://flagcdn.com/no.svg' },
  { name: 'Oman', code: 'om', flag: 'https://flagcdn.com/om.svg' },
  { name: 'Pakistan', code: 'pk', flag: 'https://flagcdn.com/pk.svg' },
  { name: 'Palau', code: 'pw', flag: 'https://flagcdn.com/pw.svg' },
  { name: 'Palestine', code: 'ps', flag: 'https://flagcdn.com/ps.svg' },
  { name: 'Panama', code: 'pa', flag: 'https://flagcdn.com/pa.svg' },
  { name: 'Papua New Guinea', code: 'pg', flag: 'https://flagcdn.com/pg.svg' },
  { name: 'Paraguay', code: 'py', flag: 'https://flagcdn.com/py.svg' },
  { name: 'Peru', code: 'pe', flag: 'https://flagcdn.com/pe.svg' },
  { name: 'Philippines', code: 'ph', flag: 'https://flagcdn.com/ph.svg' },
  { name: 'Poland', code: 'pl', flag: 'https://flagcdn.com/pl.svg' },
  { name: 'Portugal', code: 'pt', flag: 'https://flagcdn.com/pt.svg' },
  { name: 'Qatar', code: 'qa', flag: 'https://flagcdn.com/qa.svg' },
  { name: 'Romania', code: 'ro', flag: 'https://flagcdn.com/ro.svg' },
  { name: 'Russia', code: 'ru', flag: 'https://flagcdn.com/ru.svg' },
  { name: 'Rwanda', code: 'rw', flag: 'https://flagcdn.com/rw.svg' },
  { name: 'Saint Kitts and Nevis', code: 'kn', flag: 'https://flagcdn.com/kn.svg' },
  { name: 'Saint Lucia', code: 'lc', flag: 'https://flagcdn.com/lc.svg' },
  { name: 'Saint Vincent and the Grenadines', code: 'vc', flag: 'https://flagcdn.com/vc.svg' },
  { name: 'Samoa', code: 'ws', flag: 'https://flagcdn.com/ws.svg' },
  { name: 'San Marino', code: 'sm', flag: 'https://flagcdn.com/sm.svg' },
  { name: 'Sao Tome and Principe', code: 'st', flag: 'https://flagcdn.com/st.svg' },
  { name: 'Saudi Arabia', code: 'sa', flag: 'https://flagcdn.com/sa.svg' },
  { name: 'Senegal', code: 'sn', flag: 'https://flagcdn.com/sn.svg' },
  { name: 'Serbia', code: 'rs', flag: 'https://flagcdn.com/rs.svg' },
  { name: 'Seychelles', code: 'sc', flag: 'https://flagcdn.com/sc.svg' },
  { name: 'Sierra Leone', code: 'sl', flag: 'https://flagcdn.com/sl.svg' },
  { name: 'Singapore', code: 'sg', flag: 'https://flagcdn.com/sg.svg' },
  { name: 'Slovakia', code: 'sk', flag: 'https://flagcdn.com/sk.svg' },
  { name: 'Slovenia', code: 'si', flag: 'https://flagcdn.com/si.svg' },
  { name: 'Solomon Islands', code: 'sb', flag: 'https://flagcdn.com/sb.svg' },
  { name: 'Somalia', code: 'so', flag: 'https://flagcdn.com/so.svg' },
  { name: 'South Africa', code: 'za', flag: 'https://flagcdn.com/za.svg' },
  { name: 'South Sudan', code: 'ss', flag: 'https://flagcdn.com/ss.svg' },
  { name: 'Spain', code: 'es', flag: 'https://flagcdn.com/es.svg' },
  { name: 'Sri Lanka', code: 'lk', flag: 'https://flagcdn.com/lk.svg' },
  { name: 'Sudan', code: 'sd', flag: 'https://flagcdn.com/sd.svg' },
  { name: 'Suriname', code: 'sr', flag: 'https://flagcdn.com/sr.svg' },
  { name: 'Sweden', code: 'se', flag: 'https://flagcdn.com/se.svg' },
  { name: 'Switzerland', code: 'ch', flag: 'https://flagcdn.com/ch.svg' },
  { name: 'Syria', code: 'sy', flag: 'https://flagcdn.com/sy.svg' },
  { name: 'Taiwan', code: 'tw', flag: 'https://flagcdn.com/tw.svg' },
  { name: 'Tajikistan', code: 'tj', flag: 'https://flagcdn.com/tj.svg' },
  { name: 'Tanzania', code: 'tz', flag: 'https://flagcdn.com/tz.svg' },
  { name: 'Thailand', code: 'th', flag: 'https://flagcdn.com/th.svg' },
  { name: 'Togo', code: 'tg', flag: 'https://flagcdn.com/tg.svg' },
  { name: 'Tonga', code: 'to', flag: 'https://flagcdn.com/to.svg' },
  { name: 'Trinidad and Tobago', code: 'tt', flag: 'https://flagcdn.com/tt.svg' },
  { name: 'Tunisia', code: 'tn', flag: 'https://flagcdn.com/tn.svg' },
  { name: 'Turkey', code: 'tr', flag: 'https://flagcdn.com/tr.svg' },
  { name: 'Turkmenistan', code: 'tm', flag: 'https://flagcdn.com/tm.svg' },
  { name: 'Tuvalu', code: 'tv', flag: 'https://flagcdn.com/tv.svg' },
  { name: 'Uganda', code: 'ug', flag: 'https://flagcdn.com/ug.svg' },
  { name: 'Ukraine', code: 'ua', flag: 'https://flagcdn.com/ua.svg' },
  { name: 'United Arab Emirates', code: 'ae', flag: 'https://flagcdn.com/ae.svg' },
  { name: 'United Kingdom', code: 'gb', flag: 'https://flagcdn.com/gb.svg' },
  { name: 'United States', code: 'us', flag: 'https://flagcdn.com/us.svg' },
  { name: 'Uruguay', code: 'uy', flag: 'https://flagcdn.com/uy.svg' },
  { name: 'Uzbekistan', code: 'uz', flag: 'https://flagcdn.com/uz.svg' },
  { name: 'Vanuatu', code: 'vu', flag: 'https://flagcdn.com/vu.svg' },
  { name: 'Vatican City', code: 'va', flag: 'https://flagcdn.com/va.svg' },
  { name: 'Venezuela', code: 've', flag: 'https://flagcdn.com/ve.svg' },
  { name: 'Vietnam', code: 'vn', flag: 'https://flagcdn.com/vn.svg' },
  { name: 'Yemen', code: 'ye', flag: 'https://flagcdn.com/ye.svg' },
  { name: 'Zambia', code: 'zm', flag: 'https://flagcdn.com/zm.svg' },
  { name: 'Zimbabwe', code: 'zw', flag: 'https://flagcdn.com/zw.svg' },
];

export default countries;
